language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

services:
  - redis

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - yes '' | pecl install apcu
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enabled = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.use_request_time = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer install --no-interaction

script: ./vendor/bin/phpunit

jobs:
  include:
    - stage: Static analysis
      script: vendor/bin/phpstan analyse

    - stage: Coding standards
      script: ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

    - stage: Code coverage
      script:
        - ./vendor/bin/phpunit --coverage-text --coverage-clover=clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover clover.xml
